<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>MediaCli.Transcode</RootNamespace>
    <AssemblyName>MediaCli.Transcode</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="YamlDotNet" Version="16.*" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\presets\default.yaml" Link="presets\default.yaml" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
